name: Build Wheel
on:
  push:
    branches:
      - ci-wheel
    tags:
      - "v[0-9]+*"

env:
  TORCH_CUDA_ARCH_LIST: "8.0 8.6 8.9+PTX"  # Need fix for 9.0
  PUNICA_CI_TORCH_VERSION: "2.1.0"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]
        cuda: ["11.8", "12.1"]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheel
        run: |
          chown -R $CI_UID:$CI_GID "$GITHUB_WORKSPACE"
          version="$(cat version.txt)"
          docker run --rm -t \
              -v "$CI_RUNNER_CACHE_DIR":/ci-cache \
              -v "$GITHUB_WORKSPACE":/app \
              -e PUNICA_CI_PYTHON_VERSION=${{ matrix.python }} \
              -e PUNICA_CI_CUDA_VERSION=${{ matrix.cuda }} \
              -e PUNICA_CI_TORCH_VERSION=$PUNICA_CI_TORCH_VERSION \
              -e PUNICA_BUILD_VERSION=$version \
              -e TORCH_CUDA_ARCH_LIST="$TORCH_CUDA_ARCH_LIST" \
              --user $CI_UID:$CI_GID \
              pytorch/manylinux-builder:cuda${{ matrix.cuda }} \
              bash /app/ci/run-ci-build-wheel.bash

      - run: du -h dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-python${{ matrix.python }}-cuda${{ matrix.cuda }}
          path: dist/*
